// Author: Jon Maken, All Rights Reserved
// License: 3-clause BSD

package exec

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"bitbucket.org/jonforums/uru/env"
)

// switcher script templates
var batScript = `@ECHO OFF
REM autogenerated by uru

SET PATH=%s
SET GEM_HOME=%s
`

var ps1Script = `# autogenerated by uru

$env:PATH = "%s"
$env:GEM_HOME = "%s"
`

var bashScript = `# autogenerated by uru

export PATH=%s
`

// CreateSwitcherScript creates an environment switcher script customized to the
// type of shell calling the uru runtime.
func CreateSwitcherScript(ctx *env.Context, path *[]string, gemHome string) (scriptName string, err error) {
	scriptType := os.Getenv(`URU_INVOKER`)

	var script string
	switch scriptType {
	case `powershell`:
		script = ps1Script
		scriptName = "uru_lackee.ps1"
	case `batch`:
		script = batScript
		scriptName = "uru_lackee.bat"
	case `bash`:
		script = bashScript
		scriptName = "uru_lackee"
	default:
		panic("uru invoked from unknown shell (check URU_INVOKER env var)")
	}
	log.Printf("[DEBUG] switcher script: %s\n", scriptName)

	switcher := filepath.Join(ctx.Home(), scriptName)
	f, err := os.Create(switcher)
	if err != nil {
		panic(fmt.Sprintf("unable to create `%s` switcher script", switcher))
	}
	defer f.Close()

	if runtime.GOOS != `windows` {
		f.Chmod(0755)
	}

	// modify the bash script to suppress GEM_HOME creation when nonexistent
	var content string
	if scriptType == `bash` {
		if gemHome != `` {
			script = strings.Join([]string{script, "export GEM_HOME=%s\n"}, ``)
			content = fmt.Sprintf(script, strings.Join(*path, string(os.PathListSeparator)), gemHome)
		} else {
			script = strings.Join([]string{script, "unset GEM_HOME\n"}, ``)
			content = fmt.Sprintf(script, strings.Join(*path, string(os.PathListSeparator)))
		}
	} else {
		content = fmt.Sprintf(script, strings.Join(*path, string(os.PathListSeparator)), gemHome)
	}

	_, err = f.WriteString(content)
	if err != nil {
		panic(fmt.Sprintf("failed to write `%s` switcher script", switcher))
	}

	return
}
